export type WorkerStatus="pending"|"assigned"|"starting"|"running"|"blocked"|"waiting"|"completed"|"failed"|"cancelled"|"expired";
export interface SpawnWorkerRequest{taskId:string;tenant:string;repository:{owner:string;repo:string};role:string;assignment:unknown;requiredCapabilities?:string[];preferredModelTier?:string;maxCostUsd?:number;maxDurationMs?:number;repositoryPermissions?:Record<string,unknown>;workspaceRequirement?:unknown;dependencies?:string[];parentWorkerId?:string;coordinatorId?:string;correlationId?:string;idempotencyKey:string;maxAttempts?:number}
export interface SentientWorker{id:string;spawnRequestId:string;taskId:string;tenant:string;role:string;assignment:unknown;status:WorkerStatus;runtimeId?:string;runtimeHandle?:string;leaseOwner?:string;leaseExpiresAt?:string;lastHeartbeatAt?:string;attemptCount:number;budgetUsd?:number;spentUsd:number;parentWorkerId?:string;correlationId:string}
export interface RuntimeRequirements{capabilities:string[];preferredModelTier?:string;maxCostUsd?:number;maxDurationMs?:number;workspaceRequirement?:unknown}
export interface WorkerRuntime{readonly id:string;compatible(r:RuntimeRequirements):boolean;spawn(w:SentientWorker,r:RuntimeRequirements):Promise<{handle:string}>;assign(handle:string,assignment:unknown):Promise<void>;inspect(handle:string):Promise<{status:string;spentUsd?:number;reason?:string;result?:unknown}>;cancel(handle:string,reason:string):Promise<void>;terminate(handle:string,reason:string):Promise<void>}
const T:Record<WorkerStatus,WorkerStatus[]>={pending:["assigned","cancelled","failed"],assigned:["starting","cancelled","failed"],starting:["running","failed","cancelled","expired"],running:["blocked","waiting","completed","failed","cancelled","expired"],blocked:["running","waiting","failed","cancelled","expired"],waiting:["running","blocked","completed","failed","cancelled","expired"],completed:[],failed:[],cancelled:[],expired:[]};
export function assertWorkerTransition(a:WorkerStatus,b:WorkerStatus){if(!T[a].includes(b))throw new Error(`Illegal worker transition ${a} -> ${b}`)}
export class RuntimeRegistry{constructor(private rs:WorkerRuntime[]){}select(r:RuntimeRequirements){return this.rs.find(x=>x.compatible(r))??null}get(id:string){return this.rs.find(x=>x.id===id)??null}}
export class DeterministicWorkerRuntime implements WorkerRuntime{readonly id="deterministic";private s=new Map<string,string>();constructor(private caps:string[]=["test"]){}compatible(r:RuntimeRequirements){return r.capabilities.every(c=>this.caps.includes(c))}async spawn(w:SentientWorker){const handle=`det:${w.id}`;this.s.set(handle,"starting");return{handle}}async assign(h:string,_a:unknown){if(!this.s.has(h))throw new Error("unknown runtime handle");this.s.set(h,"running")}async inspect(h:string){return{status:this.s.get(h)??"failed"}}async cancel(h:string,_r:string){this.s.set(h,"cancelled")}async terminate(h:string,_r:string){this.s.set(h,"failed")}}
