import {randomUUID} from "node:crypto";import type{Pool}from"pg";import{assertWorkerTransition,type SentientWorker,type SpawnWorkerRequest,type WorkerStatus}from"./worker-control.js";
export class WorkerStore{constructor(private db:Pool){}
async request(x:SpawnWorkerRequest){const cid=x.correlationId??randomUUID(),r=await this.db.query(`INSERT INTO worker_spawn_requests(task_id,tenant,repository_owner,repository_name,role,subtask,required_capabilities,preferred_model_tier,max_cost_usd,max_duration_ms,repository_permissions,workspace_requirement,parent_worker_id,coordinator_id,idempotency_key,correlation_id,max_attempts)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17)ON CONFLICT(tenant,idempotency_key)DO NOTHING RETURNING id`,[x.taskId,x.tenant,x.repository.owner,x.repository.repo,x.role,x.assignment,x.requiredCapabilities??[],x.preferredModelTier??null,x.maxCostUsd??null,x.maxDurationMs??null,x.repositoryPermissions??{},x.workspaceRequirement??null,x.parentWorkerId??null,x.coordinatorId??null,x.idempotencyKey,cid,x.maxAttempts??3]);let id=r.rows[0]?.id,created=!!id;if(!id)id=(await this.db.query(`SELECT id FROM worker_spawn_requests WHERE tenant=$1 AND idempotency_key=$2`,[x.tenant,x.idempotencyKey])).rows[0].id;if(created)for(const d of x.dependencies??[])await this.db.query(`INSERT INTO worker_dependencies VALUES($1,$2)ON CONFLICT DO NOTHING`,[id,d]);if(created)await this.event(x.taskId,"WORKER_SPAWN_REQUESTED",null,{spawnRequestId:id});return{id,created}}
async claim(owner:string,ms=30000){const r=await this.db.query(`WITH c AS(SELECT id FROM worker_spawn_requests WHERE next_attempt_at<=now()AND(status='pending'OR(status='claimed'AND claim_expires_at<=now())OR status='blocked')ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1)UPDATE worker_spawn_requests SET status='claimed',claim_owner=$1,claim_expires_at=now()+$2*interval'1 millisecond' WHERE id=(SELECT id FROM c)RETURNING *`,[owner,ms]);return r.rows[0]??null}
async dependencies(id:string){return(await this.db.query(`SELECT w.id,w.status FROM worker_dependencies d JOIN sentient_workers w ON w.id=d.depends_on_worker_id WHERE d.spawn_request_id=$1`,[id])).rows}
async block(id:string,reason:string){await this.db.query(`UPDATE worker_spawn_requests SET status='blocked',claim_owner=NULL,claim_expires_at=NULL,last_error=$2 WHERE id=$1`,[id,reason])}
async reject(id:string,reason:string){const r=await this.db.query(`UPDATE worker_spawn_requests SET status='failed',last_error=$2 WHERE id=$1 RETURNING task_id`,[id,reason]);if(r.rowCount)await this.event(r.rows[0].task_id,"WORKER_FAILED",null,{reason})}
async create(q:any,runtime:string,owner:string,lease=60000){const r=await this.db.query(`INSERT INTO sentient_workers(spawn_request_id,task_id,tenant,repository_owner,repository_name,role,assignment,status,runtime_id,model_provider_requirements,capabilities,authority,workspace_assignment,budget_usd,lease_owner,lease_expires_at,parent_worker_id,coordinator_id,correlation_id,attempt_count)SELECT id,task_id,tenant,repository_owner,repository_name,role,subtask,'assigned',$2,jsonb_build_object('preferredModelTier',preferred_model_tier),required_capabilities,repository_permissions,workspace_requirement,max_cost_usd,$3,now()+$4*interval'1 millisecond',parent_worker_id,coordinator_id,correlation_id,attempt_count+1 FROM worker_spawn_requests WHERE id=$1 ON CONFLICT(spawn_request_id)DO UPDATE SET spawn_request_id=EXCLUDED.spawn_request_id RETURNING *`,[q.id,runtime,owner,lease]);await this.db.query(`UPDATE worker_spawn_requests SET status='scheduled',attempt_count=attempt_count+1,claim_owner=NULL,claim_expires_at=NULL WHERE id=$1`,[q.id]);const w=map(r.rows[0]);await this.event(w.taskId,"WORKER_ASSIGNED",w.id,{runtime});return w}
async transition(id:string,to:WorkerStatus,reason?:string){const c=await this.db.connect();try{await c.query("BEGIN");const a=await c.query(`SELECT * FROM sentient_workers WHERE id=$1 FOR UPDATE`,[id]);if(!a.rowCount)throw Error("Unknown worker");assertWorkerTransition(a.rows[0].status,to);const terminal=["completed","failed","cancelled","expired"].includes(to),r=await c.query(`UPDATE sentient_workers SET status=$2,started_at=CASE WHEN $2='running'THEN coalesce(started_at,now())ELSE started_at END,completed_at=CASE WHEN $3 THEN now()ELSE completed_at END,failure_reason=CASE WHEN $2='failed'THEN $4 ELSE failure_reason END,termination_reason=CASE WHEN $2 IN('cancelled','expired')THEN $4 ELSE termination_reason END,lease_owner=CASE WHEN $3 THEN NULL ELSE lease_owner END,lease_expires_at=CASE WHEN $3 THEN NULL ELSE lease_expires_at END WHERE id=$1 RETURNING *`,[id,to,terminal,reason??null]);await c.query("COMMIT");const w=map(r.rows[0]);await this.event(w.taskId,`WORKER_${to.toUpperCase()}`,w.id,{reason});return w}catch(e){await c.query("ROLLBACK");throw e}finally{c.release()}}
async handle(id:string,h:string){await this.db.query(`UPDATE sentient_workers SET runtime_handle=$2 WHERE id=$1`,[id,h]);return this.transition(id,"starting")}
async heartbeat(id:string,owner:string,ms=60000,spent?:number){const r=await this.db.query(`UPDATE sentient_workers SET last_heartbeat_at=now(),lease_expires_at=now()+$3*interval'1 millisecond',spent_usd=greatest(spent_usd,coalesce($4,spent_usd))WHERE id=$1 AND lease_owner=$2 AND status IN('starting','running','blocked','waiting')RETURNING task_id`,[id,owner,ms,spent??null]);if(r.rowCount)await this.event(r.rows[0].task_id,"WORKER_HEARTBEAT",id,{});return!!r.rowCount}
async stale(){return(await this.db.query(`SELECT * FROM sentient_workers WHERE status IN('starting','running','blocked','waiting')AND lease_expires_at<=now()`)).rows.map(map)}
async get(id:string){const r=await this.db.query(`SELECT * FROM sentient_workers WHERE id=$1`,[id]);if(!r.rowCount)throw Error("Unknown worker");return map(r.rows[0])}
async task(id:string){return(await this.db.query(`SELECT * FROM sentient_workers WHERE task_id=$1`,[id])).rows.map(map)}
async retry(w:SentientWorker,reason:string){const r=await this.db.query(`UPDATE worker_spawn_requests SET status=CASE WHEN attempt_count<max_attempts THEN'pending'ELSE'failed'END,next_attempt_at=now()+interval'1 second',last_error=$2 WHERE id=$1 RETURNING status`,[w.spawnRequestId,reason]);const ok=r.rows[0].status==="pending";await this.event(w.taskId,ok?"WORKER_RETRY_SCHEDULED":"WORKER_FAILED",w.id,{reason});return ok}
async event(task:string,type:string,worker:string|null,details:unknown){await this.db.query(`INSERT INTO audit_events(task_id,event_type,actor,details)VALUES($1,$2,$3,$4)`,[task,type,worker?`worker:${worker}`:"worker-control-plane",details])}}
function map(r:any):SentientWorker{return{id:r.id,spawnRequestId:r.spawn_request_id,taskId:r.task_id,tenant:r.tenant,role:r.role,assignment:r.assignment,status:r.status,runtimeId:r.runtime_id??undefined,runtimeHandle:r.runtime_handle??undefined,leaseOwner:r.lease_owner??undefined,leaseExpiresAt:r.lease_expires_at?.toISOString?.()??undefined,lastHeartbeatAt:r.last_heartbeat_at?.toISOString?.()??undefined,attemptCount:+r.attempt_count,budgetUsd:r.budget_usd==null?undefined:+r.budget_usd,spentUsd:+r.spent_usd,parentWorkerId:r.parent_worker_id??undefined,correlationId:r.correlation_id}}
